events {}

http {
    # HTTP to HTTPS redirect
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # HTTPS Server
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        location /api {
            proxy_pass http://backend:3000;
        }

        location /health {
            proxy_pass http://backend:3000;
        }

        location / {
            proxy_pass http://frontend:3000;
        }
    }
}
